// ==UserScript==
// @name         Bing Search
// @namespace    https://github.com/ArunrajAdlee/userscripts
// @version      0.4
// @description  Opens batches of randomized Bing searches in new tabs
// @author       ArunrajAdlee
// @match        https://www.bing.com/*
// @icon         https://www.google.com/s2/favicons?sz=64&domain=bing.com
// @run-at       document-idle
// @grant        none
// ==/UserScript==

(function () {
  'use strict';

  // Click the on-page button to start a run. Searches are opened in batches,
  // with a pause between batches to space them out over time.
  const SEARCHES_PER_BATCH = 4; // tabs opened per batch
  const BATCH_COUNT = 8; // number of batches per run
  const DELAY_BETWEEN_SEARCHES_MS = 7500;
  const DELAY_BETWEEN_BATCHES_MS = 16 * 60 * 1000; // 16 minutes
  const AUTO_CLOSE_DELAY_MS = 3500; // how long an opened search tab stays open

  const TRIGGER_BUTTON_ID = 'bing-search-trigger-button';

  const sleep = (ms) => new Promise((resolve) => setTimeout(resolve, ms));

  // Pool of search terms; one is picked at random for each search.
  const SEARCH_TERMS = [
    'where is my refund',
    'when is easter',
    'how many ounces in a cup',
    'what time is it',
    'when is easter 2025',
    'how many weeks in a year',
    'how to screenshot on mac',
    'what is my ip',
    'what is my ip address',
    'what to watch',
    'how to buy dogecoin on etoro',
    'how many ounces in a gallon',
    'when is the full moon',
    'how many ounces in a pound',
    'what time is it in california',
    'what time is sunset',
    'how to screenshot on windows',
    'when is the next full moon',
    'when is daylight savings',
    'how many cups in a quart',
    'how many grams in an ounce',
    'when does spring start',
    'when does the time change',
    'how late is the closest grocery store open',
    "how to solve a rubik's cube",
    'how many liters in a gallon',
    'how many oz in a gallon',
    'how to delete instagram account',
    'how many oz in a cup',
    'how to tie a tie',
    'when is the superbowl',
    'who won the superbowl',
    'how many centimeters in an inch',
    'how long to boil eggs',
    'what song is this',
    'when does the super bowl start',
    'why are flags at half mast today',
    'how many teaspoons in a tablespoon',
    'how many quarts in a gallon',
    'when is the first day of spring',
    'when is mothers day',
    'where is the super bowl this year',
    'who is playing in the super bowl',
    'what time is it in hawaii',
    'how to lose weight fast',
    'how many feet in a mile',
    'what time is it in arizona',
    'what killed mickey mouse',
    'is bronchitis contagious',
    'what happened to damar hamlin',
    'when does march madness start',
    'how old is hasbulla',
    'what is the weather today',
    'how many steps in a mile',
    'how many tablespoons in a cup',
    'when is the next mega millions drawing',
    'how old was elvis when he died',
    'is gwen stefani pregnant',
    'when is spring',
    'how many oz in a pound',
    'how to take a screenshot on mac',
    'how many cups in a gallon',
    'how many grams in a pound',
    'what is lupus',
    'what is today',
    'did anyone win mega millions',
    'how many ounces in a quart',
    'how to write a check',
    'how to pronounce',
    'how to watch the super bowl',
    'where to watch the super bowl',
    'how many episodes of the last of us',
    'what time is it in australia',
    'is shingles contagious',
    'how to lower blood pressure',
    'how many ounces in a liter',
    'how old is rihanna',
    'youtube',
    'weather',
    'amazon',
    'facebook',
    'google',
    'wordle',
    'gmail',
    'walmart',
    'google translate',
    'nfl',
    'fox news',
    'yahoo mail',
    'home depot',
    'yahoo',
    'weather tomorrow',
    'nba',
    'translate',
    'traductor',
    'google maps',
    'food near me',
    'ebay',
    'target',
    'restaurants near me',
    'instagram',
    'twitter',
    'cnn',
    'damar hamlin',
    'espn',
    'news',
    'costco',
    'amazon prime',
    'nfl scores',
    'english to spanish',
    'chatgpt',
    'zillow',
    'indeed',
    'nba scores',
    'google flights',
    'best buy',
    'calculator',
    'smm panel',
    'usps tracking',
    'google docs',
    'mcdonalds',
    'craigslist',
    'lowes',
    'tiempo',
    "where's my refund",
    'lakers',
    'shein',
    'weather 10 days',
    'starbucks',
    'wells fargo',
    'maps',
    'msn',
    'netflix',
    'gmail login',
    'walgreens',
    'bank of america',
    'traductor español ingles',
    'etsy',
    'super bowl',
    'chick fil a',
    'speed test',
    'facebook login',
    'linkedin',
    'hotmail',
    'dominos',
    'omegle',
    'spanish to english',
    'ups tracking',
    'cvs',
    'usps',
    'macys',
    'airbnb',
    'roblox',
    'american airlines',
    'dow jones',
    'aol mail',
    'kohls',
    'mega millions',
    'chat gpt',
    "sam's club",
    'capital one',
    'you',
    'pizza hut',
    't mobile',
    'google classroom',
    'solitaire',
    'pinterest',
    'translate english to spanish',
    'the last of us',
    'soap2day',
    'premier league',
    'outlook',
    'google drive',
    'reddit',
    'autozone',
    'canva',
    'Life Is Strange 2 – Episode 2: Rules',
    'My Memory of Us',
    'Pikuniku',
    'Resident Evil 2',
    'Kingdom Hearts III',
    'Penguin Wars',
    'Sphinx and the Cursed Mummy',
    'Dragon Marked For Death',
    'Piczle Colors',
    'Planetarian: The Reverie of a Little Planet',
    'Robotics;Notes DaSH',
    'Robotics;Notes Elite HD',
    'Sunless Skies',
    'Ace Combat 7: Skies Unknown',
    'Wargroove',
    'Apex Legends',
    'The Book of Unwritten Tales 2',
    'Etrian Odyssey Nexus',
    'V-Rally 4',
    'BlazBlue: Central Fiction',
    'God Eater 3',
    'Monster Energy Supercross - The Official Videogame 2',
    'Space Engineers',
    'Conarium',
    'The Liar Princess and the Blind Prince',
    'Final Fantasy IX',
    'Tetris 99',
    'Crackdown 3',
    'DreamWorks Dragons Dawn of New Riders',
    'Far Cry New Dawn',
    'Jump Force',
    'Metro Exodus',
    '8-bit ADV Steins;Gate',
    'Death end re;Quest',
    'Steins;Gate Elite',
    'Steins;Gate: Linear Bounded Phenogram',
    'Yakuza Kiwami',
    'Aragami: Shadow Edition',
    'Phoenix Wright: Ace Attorney Trilogy',
    'Spirit Hunter: NG',
    'Anthem',
    'Dirt Rally 2.0',
    'The Lego Movie 2 Videogame',
    'Stellaris: Console Edition',
    'Trials Rising',
    'Dies irae: Interview with Kaziklu Bey',
    'Alien League',
    'Dead or Alive 6',
    'Swords and Soldiers 2 Shawarmageddon',
    'ToeJam & Earl: Back in the Groove',
    'Left Alive',
    'The Occupation',
    'R.B.I. Baseball 19',
    'Overload',
    'Flowers: Les Quatre Saisons',
    'Devil May Cry 5',
    "Kirby's Extra Epic Yarn",
    'The Caligula Effect: Overdose',
    'Hypnospace Outlaw',
    'Mystery Dungeon: Shiren the Wanderer',
    'Baba Is You',
    'Bonds of the Skies',
    'Mystery Dungeon: Shiren the Wanderer',
    'One Piece: World Seeker',
    'Sephirothic Stories',
    "Tom Clancy's The Division 2",
    'America Ninja Warrior Challenge',
    'Fate/EXTELLA LINK',
    'Super Robot Wars T',
    'Sekiro: Shadows Die Twice',
    'Unravel Two',
    'Final Fantasy VII',
    'Generation Zero',
    'The Legend of Heroes: Trails of Cold Steel',
    'MLB The Show 19',
    'Nelke & the Legendary Alchemists: Ateliers of the New World',
    'Outward',
    'Power Rangers: Battle for the Grid',
    'The Walking Dead: The Final Season – Episode 4: Take Us Back',
    'Xenon Racer',
    'Fun! Fun! Animal Park',
    "Assassin's Creed III Remastered",
    'Operencia: The Stolen Sun',
    'Tropico 6',
    'Unheard',
    "Yoshi's Crafted World",
    'Darksiders: Warmastered Edition',
    'FAR: Lone Sails',
    'Power Rangers: Battle for the Grid',
    "Frane: Dragons' Odyssey",
    'Islanders',
    'Spirit Hunter: Death Mark',
    'Super Dragon Ball Heroes: World Mission',
    'Dangerous Driving',
    'Phoenix Wright: Ace Attorney Trilogy',
    'Zanki Zero: Last Beginning',
    'Earth Defense Force: Iron Rain',
    "Hellblade: Senua's Sacrifice",
    'Code 7: Episode 2 — Memory and Episode 3 — Backdoor',
    'Nintendo Labo Toy-Con 04: VR Kit',
    'Konami Arcade Classics',
    'Anno 1800',
    'Final Fantasy X/X-2 HD Remaster',
    'My Time at Portia',
    'World War Z',
    'Cuphead',
    'Katana Zero',
    "Dragon's Dogma: Dark Arisen",
    'Mortal Kombat 11',
    'Imperator: Rome',
    'Picross S3',
    'SteamWorld Quest: Hand of Gilgamech',
    'Umihara Kawase Fresh!',
    'BoxBoy! + BoxGirl!',
    'Days Gone',
    'Final Fantasy XII: The Zodiac Age',
    'UBOAT',
    'Detective Di: The Silk Rose Murders',
    'Close to the Sun',
    'Puyo Puyo Champions',
    'Shakedown: Hawaii',
    'Life Is Strange 2 – Episode 3: Wastelands',
    'Yakuza Kiwami 2',
    'Saints Row: The Third - The Full Package',
    'A Plague Tale: Innocence',
    'Darkwood',
    'Rage 2',
    'Redout',
    'Sniper Elite V2 Remastered',
    'World End Syndrome',
    'Bubsy: Paws on Fire!',
    'Castlevania Anniversary Collection',
    'Darkwood',
    'Darkwood',
    "Assassin's Creed III Remastered",
    'Atelier Lulua: The Scion of Arland',
    'Dauntless',
    'Observation',
    'Resident Evil',
    'Resident Evil 4',
    'Resident Evil Zero',
    'Slay the Spire',
    'Team Sonic Racing',
    'Pokémon Rumble Rush',
    'Total War: Three Kingdoms',
    'Little Friends: Dogs & Cats',
    'Among the Sleep: Enhanced Edition',
    'Blood & Truth',
    'Brothers: A Tale of Two Sons',
    'Crystal Crisis',
    'The House in Fata Morgana: Dream of the Revenants Edition',
    'Layers of Fear 2',
    'Void Bastards',
    'Vectronom',
    'Outer Wilds',
    'Cricket 19',
    'PixARK',
    'Asdivine Dios',
    'Kotodama: The 7 Mysteries of Fujisawa',
    'The Legend of Heroes: Trails of Cold Steel II',
    'Persona Q2: New Cinema Labyrinth',
    'Timespinner',
    'Warhammer: Chaosbane',
    'Journey',
    'MotoGP 19',
    'Slay the Spire',
    'A-Train Express',
    'Octopath Traveler',
    'Battle Worlds: Kronos',
    'Collection of Mana',
    'Contra Anniversary Collection',
    'The House in Fata Morgana: Dream of the Revenants Edition',
    "Doraemon: Nobita's Story of Seasons",
    'Cadence of Hyrule',
    'Blaster Master Zero',
    'Bloodstained: Ritual of the Night',
    'Crystal Crisis',
    '198X',
    'Harry Potter: Wizards Unite',
    'My Friend Pedro',
    'Project Lux',
    'Super Neptunia RPG',
    'Yakuza 5',
    'Yo-kai Watch 4',
    'Crash Team Racing Nitro-Fueled',
    'Heavy Rain',
    'Bloodstained: Ritual of the Night',
    'Devil May Cry',
    'Judgment',
    'Samurai Shodown',
    'Super Neptunia RPG',
    'Hardcore Mecha',
    'Human: Fall Flat',
    'Minit',
    'MotoGP 19',
    'The Sinking City',
    'F1 2019',
    'Super Mario Maker 2',
    'Final Fantasy XIV: Shadowbringers',
    'Psyvariar Delta',
    'Red Faction: Guerrilla Re-Mars-tered',
    'Alternate Jake Hunter: Daedalus The Awakening of Golden Jazz',
    'Clannad',
    'Stranger Things 3: The Game',
    'Attack on Titan 2: Final Battle',
    'Sea of Solitude',
    'Teppen',
    'Dr. Mario World',
    'Senran Kagura: Peach Ball',
    'Umihara Kawase Fresh!',
    'Blazing Chrome',
    'Earth Defense Force 5',
    'Tiny Metal: Full Metal Rumble',
    'Aggelos',
    'Dragon Quest Builders 2',
    'God Eater 3',
    'Etherborn',
    'Sky: Children of the Light',
    'Lost Ember',
    'Marvel Ultimate Alliance 3: The Black Order',
    'Beyond: Two Souls',
    'Pokémon Rumble Rush',
    'Tetris Effect',
    'Vane',
    'Hyper Light Drifter',
    "Raiden V: Director's Cut",
    'Fire Emblem: Three Houses',
    'Kill la Kill: If',
    'Wolfenstein: Cyberpilot',
    'Wolfenstein: Youngblood',
    'Mutant Year Zero: Road to Eden: Deluxe Edition',
    'Oxygen Not Included',
    'Crystal Crisis',
    'The Church in the Darkness',
    'Dry Drowning',
    'Horsey, Listen!',
    'Madden NFL 20',
    'Asdivine Menace',
    'Age of Wonders: Planetfall',
    "Illusion of L'Phalcia",
    'Metal Wolf Chaos XD',
    'Pillars of Eternity: Complete Edition',
    'Sword Art Online: Fatal Bullet Complete Edition',
    'Anodyne 2 - Return to Dust',
    "The Bard's Tale Trilogy",
    'Friday the 13th: The Game',
    'Rebel Galaxy Outlaw',
    'Ion Fury',
    'Vasara HD Collection',
    'Grandia HD Collection',
    'FAR: Lone Sails',
    'Rad',
    'Remnant: From the Ashes',
    'Yakuza 3',
    'Yu-Gi-Oh! Legacy of the Duelist: Link Evolution',
    'Life Is Strange 2 – Episode 4: Faith',
    'Oninaki',
    'Tokyo Chronos',
    'Ancestors: The Humankind Odyssey',
    "The Bard's Tale IV: Director's Cut",
    'Control',
    'Crystar',
    'Hunt: Showdown',
    'Minoria',
    'World of Warcraft Classic',
    'Pokémon Masters',
    'Azur Lane: Crosswave',
    'Bubsy: Paws on Fire!',
    'Astral Chain',
    'Blair Witch',
    'Psychedelica of the Ashen Hawk',
    'The Dark Pictures: Man of Medan',
    'The Ninja Saviors: Return of the Warriors',
    'Catherine: Full Body',
    'Children of Morta',
    'Final Fantasy VIII Remastered',
    'Last Oasis',
    'Root Letter: Last Answer',
    'Spyro Reignited Trilogy',
    'Deadly Premonition: Origins',
    'Divinity: Original Sin II',
    'River City Girls',
    'Monster Hunter World: Iceborne',
    'NBA 2K20',
    'Caravan Stories',
    'eFootball Pro Evolution Soccer 2020',
    'Gears 5',
    'GreedFall',
    'Utawarerumono Zan',
    'Borderlands 3',
    'Daemon X Machina',
    'NHL 20',
    'AI: The Somnium Files',
    'Lego Jurassic World',
    'Reel Fishing: Road Trip Adventure',
    'Devil May Cry 2',
    'Sayonara Wild Hearts',
    'Shakedown: Hawaii',
    'Shantae and the Seven Sirens',
    'Sonic Racing',
    "The Legend of Zelda: Link's Awakening",
    'Untitled Goose Game',
    'Ni no Kuni: Wrath of the White Witch',
    'Ni no Kuni: Wrath of the White Witch Remastered',
    "Baldur's Gate: Enhanced Edition",
    "Baldur's Gate: Siege of Dragonspear",
    "Baldur's Gate II: Enhanced Edition",
    'Contra: Rogue Corps',
    'Icewind Dale: Enhanced Edition',
    'Planescape: Torment: Enhanced Edition',
    'The Surge 2',
    'Mario Kart Tour',
    'Darksiders II: Deathinitive Edition',
    'Gunvolt Chronicles: Luminous Avenger iX',
    'Ys IX: Monstrum Nox',
    'Code Vein',
    'Dragon Quest',
    'Dragon Quest II',
    'Dragon Quest III',
    'Dragon Quest XI S',
    'FIFA 20',
    'Memorrha',
    'Ori and the Blind Forest',
    'Tropico 6',
    'Cube World',
    'Call of Duty: Mobile',
    'Destiny 2: Shadowkeep',
    'Mobile Suit Gundam: Battle Operation 2',
    'ReadySet Heroes',
    'What the Golf?',
    'YU-NO: A Girl Who Chants Love at the Bound of this World',
    'One Night Stand',
    'Fault Milestone One',
    'Ciconia When They Cry – Phase 1: For You, the Replaceable Ones',
    'Ghostbusters: The Video Game Remastered',
    'One Night Stand',
    "Tom Clancy's Ghost Recon Breakpoint",
    'Shantae and the Seven Sirens',
    'The Alliance Alive HD Remastered',
    'BurgerTime Party!',
    'Concrete Genie',
    'Trine 4: The Nightmare Prince',
    'Indivisible',
    'Yooka-Laylee and the Impossible Lair',
    'Corpse Party: Blood Drive',
    'River City Melee Mach!!',
    'Spirit Hunter: NG',
    'Valfaris',
    'Doraemon Story of Seasons',
    'Frostpunk',
    'Grid',
    'Killer Queen Black',
    'Children of Morta',
    'Disco Elysium',
    'Earth Defense Force: Iron Rain',
    'Grandia HD Remaster',
    'Overwatch: Legendary Edition',
    'Steins;Gate Elite',
    'The Witcher 3: Wild Hunt Complete Edition',
    'Little Town Hero',
    'Monkey King: Hero is Back',
    'Stranded Sails: Explorers of the Cursed Islands',
    'The Jackbox Party Pack 6',
    'Travis Strikes Again: No More Heroes Complete Edition',
    'Vectronom',
    'Digimon Story Cyber Sleuth: Complete Edition',
    "Ice Age: Scrat's Nutty Adventure",
    'Plants vs Zombies: Battle for Neighborville',
    'Return of the Obra Dinn',
    'Ring Fit Adventure',
    'Raging Loop',
    'The Legend of Heroes: Trails of Cold Steel III',
    'Skullgirls 2nd Encore',
    'WWE 2K20',
    'Corpse Party 2: Dead Patient – Chapter 1',
    'Dusk Diver',
    'Call of Duty: Modern Warfare',
    'MediEvil',
    'The Outer Worlds',
    'Afterparty',
    'Atelier Ryza: Ever Darkness & the Secret Hideout',
    'Disgaea 4 Complete+',
    'Harvest Moon: Mad Dash',
    'Resident Evil 5',
    'Resident Evil 6',
    'Super Monkey Ball: Banana Blitz HD',
    'Vampyr',
    'Yakuza 4',
    'Ghost Parade',
    "Luigi's Mansion 3",
    'Spirit of the North',
    'Just Dance 2020',
    'Mario & Sonic at the Olympic Games Tokyo 2020',
    'Planet Zoo',
    'Red Dead Redemption 2',
    'Valfaris',
    'Death Stranding',
    'Disney Tsum Tsum Festival',
    'Golem',
    "Layton's Mystery Journey: Katrielle and the Millionaire's Conspiracy – Deluxe Edition",
    'Need for Speed Heat',
    "New Super Lucky's Tale",
    'Valfaris',
    'Romancing SaGa 3',
    'Last Labyrinth',
    'Age of Empires II: Definitive Edition',
    'War of the Visions: Final Fantasy Brave Exvius',
    'Pokémon Sword and Shield',
    'Star Wars Jedi: Fallen Order',
    'Tokyo Ghoul: re Call to Exist',
    'Football Manager 2020',
    'Shenmue III',
    'Children of Morta',
    'Sniper: Ghost Warrior Contracts',
    'Cyber Troopers Virtual-On Masterpiece 1995~2001',
    'SD Gundam G Generation Cross Rays',
    'Blair Witch',
    'Halo: Reach',
    'Life Is Strange 2 – Episode 5: Wolves',
    'Neverwinter Nights: Enhanced Edition',
    'Phoenix Point',
    'SaGa: Scarlet Grace - Ambitions',
    'Terminator: Resistance',
    'Alien: Isolation',
    'Darksiders Genesis',
    'Interrogation',
    'Raging Loop',
    'Star Ocean: First Departure R',
    'Ancestors: The Humankind Odyssey',
    'Dragon Quest Builders 2',
    'MechWarrior 5: Mercenaries',
    'Shovel Knight: King of Cards',
    'Shovel Knight: Showdown',
    'Steins;Gate 0',
    "Steins;Gate: My Darling's Embrace",
    'Vampire: The Masquerade – Coteries of New York',
    'Detroit: Become Human',
    'Touhou Project Genso Skydrift',
    'Path of the Warrior',
    'Project Sakura Wars',
    'Wattam',
    'Brain Age: Nintendo Switch Training',
  ];

  function randomTerm() {
    return SEARCH_TERMS[Math.floor(Math.random() * SEARCH_TERMS.length)];
  }

  // Format milliseconds as m:ss for the countdown display.
  function formatDuration(ms) {
    const totalSeconds = Math.ceil(ms / 1000);
    const minutes = Math.floor(totalSeconds / 60);
    const seconds = totalSeconds % 60;
    return `${minutes}:${String(seconds).padStart(2, '0')}`;
  }

  // Sleep for ms, calling onTick(remainingMs) about once a second so the caller
  // can show a live countdown.
  async function countdown(ms, onTick) {
    const endTime = Date.now() + ms;
    let remaining = ms;
    while (remaining > 0) {
      onTick(remaining);
      await sleep(Math.min(1000, remaining));
      remaining = endTime - Date.now();
    }
  }

  // Open one batch of searches, each in its own tab, spaced out in time.
  // report(text) is called as progress changes so the UI can reflect it.
  async function runSearchBatch(batchIndex, report) {
    for (let i = 0; i < SEARCHES_PER_BATCH; i++) {
      report(
        `Batch ${batchIndex + 1}/${BATCH_COUNT} · opening search ${i + 1}/${SEARCHES_PER_BATCH}`,
      );
      // autoClose=true tells the opened tab (also running this script) to close
      // itself shortly after loading.
      const url = `https://www.bing.com/search?q=${encodeURIComponent(
        randomTerm(),
      )}&autoClose=true`;
      window.open(url, '_blank');
      await sleep(DELAY_BETWEEN_SEARCHES_MS);
    }
  }

  // Run every batch, pausing between them to space the searches out over time.
  // report(text) is called as the state changes so the button can show progress.
  async function runAllBatches(report) {
    for (let i = 0; i < BATCH_COUNT; i++) {
      await runSearchBatch(i, report);
      if (i < BATCH_COUNT - 1) {
        await countdown(DELAY_BETWEEN_BATCHES_MS, (remaining) =>
          report(
            `Batch ${i + 1}/${BATCH_COUNT} done · next in ${formatDuration(remaining)}`,
          ),
        );
      }
    }
  }

  // A floating button to start a run and show its progress, top-right.
  function addTriggerButton() {
    if (document.getElementById(TRIGGER_BUTTON_ID)) return;

    const IDLE_LABEL = 'Start searches';

    const button = document.createElement('button');
    button.id = TRIGGER_BUTTON_ID;
    button.textContent = IDLE_LABEL;
    Object.assign(button.style, {
      position: 'fixed',
      top: '60px',
      right: '20px',
      zIndex: '99999',
      padding: '10px 16px',
      fontSize: '14px',
      color: '#fff',
      background: '#0078d4',
      border: 'none',
      borderRadius: '6px',
      cursor: 'pointer',
      boxShadow: '0 2px 6px rgba(0, 0, 0, 0.3)',
      whiteSpace: 'nowrap',
    });

    const setStatus = (text) => {
      button.textContent = text;
    };

    button.addEventListener('click', async () => {
      if (button.disabled) return;
      button.disabled = true;
      button.style.opacity = '0.6';
      button.style.cursor = 'default';
      try {
        await runAllBatches(setStatus);
        setStatus('All searches done ✓');
        await sleep(5000);
      } finally {
        button.disabled = false;
        button.style.opacity = '';
        button.style.cursor = 'pointer';
        setStatus(IDLE_LABEL);
      }
    });

    document.body.appendChild(button);
  }

  // A search tab opened by this script closes itself shortly after loading;
  // otherwise this is the main tab, which shows the trigger button.
  if (window.location.search.includes('autoClose=true')) {
    sleep(AUTO_CLOSE_DELAY_MS).then(() => window.close());
  } else {
    addTriggerButton();
  }
})();
